export type Product={id:string;title:string;description:string;category:string;price:number;stock:number;image:string;photos:string[]};
export type Banner={id:string;title:string;description:string;image:string;link:string;label:string;position:number};
export type Content={products:Product[];categories:{id:string;title:string}[];banners:Banner[];settings:{brand:string;about:string;email:string;instagram:string;whatsapp?:string}};
export const initial:Content={categories:[{id:'velas',title:'Velas Aromáticas'},{id:'kits',title:'Kits e Acessórios'},{id:'essencias',title:'Essências'}],products:[
{id:'vela-ambar',title:'Vela Âmbar & Baunilha',description:'Notas envolventes para os seus momentos de pausa. Produto ilustrativo; personalize os detalhes no painel.',category:'velas',price:7900,stock:18,image:'/images/hero.webp',photos:[]},
{id:'vela-lavanda',title:'Vela Lavanda Serena',description:'Um convite a desacelerar, com notas florais delicadas. Produto ilustrativo.',category:'velas',price:6900,stock:12,image:'/images/hero.webp',photos:[]},
{id:'kit-ritual',title:'Kit Ritual da Vela',description:'Tesoura de pavio e acessórios para cuidar dos seus rituais. Produto ilustrativo.',category:'kits',price:12900,stock:8,image:'/images/hero.webp',photos:[]},
{id:'essencia',title:'Essência Botânica',description:'Inspire novos aromas no seu espaço. Produto ilustrativo.',category:'essencias',price:3900,stock:24,image:'/images/hero.webp',photos:[]}],banners:[{id:'b1',title:'Acenda a calma.\nSinta o momento.',description:'Velas, essências e pequenos rituais para transformar a sua casa em um lugar de acolhimento.',image:'/images/hero.webp',link:'/#catalogo',label:'Encontre seu aroma',position:0},{id:'b2',title:'Pequenos rituais.\nGrandes sensações.',description:'Conheça os acessórios que tornam cada momento ainda mais especial.',image:'/images/hero.webp',link:'/?categoria=kits#catalogo',label:'Explorar os kits',position:1},{id:'b3',title:'A natureza,\nmais perto de você.',description:'Descubra notas e combinações para dar uma nova atmosfera ao seu lar.',image:'/images/hero.webp',link:'/?categoria=essencias#catalogo',label:'Conhecer essências',position:2}],settings:{brand:'Lumina',about:'Acreditamos na beleza de desacelerar. Em uma luz suave, em um aroma que abraça, no tempo dedicado a você. Nossa curadoria reúne velas, essências e acessórios para transformar pequenos gestos em momentos especiais.',email:'',instagram:'',whatsapp:'5581996149622'}};
export const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n/100);
